scenchive/Scenchive_BE

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/ScenchiveApplication.java, Scenchive/src/main/java/com/example/scenchive/domain/BaseTimeEntity.java, Scenchive/src/main/java/com/example/scenchive/domain/Board.java, Scenchive/src/main/java/com/example/scenchive/domain/BoardRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/MemberRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/boardType.java, Scenchive/src/main/java/com/example/scenchive/service/LoginService.java, Scenchive/src/main/java/com/example/scenchive/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/service/NotCorrespondingEmailException.java, Scenchive/src/main/java/com/example/scenchive/web/LoginController.java, Scenchive/src/main/java/com/example/scenchive/web/LoginForm.java, Scenchive/src/main/java/com/example/scenchive/web/MemberController.java, Scenchive/src/main/java/com/example/scenchive/web/MemberForm.java, Scenchive/src/main/java/com/example/scenchive/web/SessionConst.java, Scenchive/src/main/resources/application.properties, Scenchive/src/test/java/com/example/scenchive/service/MemberServiceTest.java
회원가입, 로그인 기능 개발
회원가입 시 중복 닉네임인 경우 예외 메시지 전달
아직 데이터베이스가 없어서 내 로컬에 있는 테스트용 db에 연결해뒀는데 이 부분 수정 필요..
=> Feat: 로그인, 회원가입 기능 구현

Scenchive/src/main/java/com/example/scenchive/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/board/repository/Board.java, Scenchive/src/main/java/com/example/scenchive/board/repository/BoardRepository.java, Scenchive/src/main/java/com/example/scenchive/board/repository/boardType.java, Scenchive/src/main/java/com/example/scenchive/board/service/BoardService.java, Scenchive/src/main/java/com/example/scenchive/member/controller/LoginController.java, Scenchive/src/main/java/com/example/scenchive/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/member/exception/NotCorrespondingEmailException.java, Scenchive/src/main/java/com/example/scenchive/member/service/LoginService.java
=> 커뮤니티 구현 완료

Scenchive/.gitignore, Scenchive/src/main/java/com/example/scenchive/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/board/dto/BoardListResponseDto.java, Scenchive/src/main/java/com/example/scenchive/board/dto/BoardResponseDto.java, Scenchive/src/main/java/com/example/scenchive/board/dto/BoardSaveRequestDto.java, Scenchive/src/main/java/com/example/scenchive/board/dto/BoardUpdateRequestDto.java, Scenchive/src/main/java/com/example/scenchive/board/service/BoardService.java, Scenchive/src/main/java/com/example/scenchive/member/controller/LoginController.java, Scenchive/src/main/java/com/example/scenchive/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/member/dto/MemberForm.java, Scenchive/src/main/java/com/example/scenchive/member/service/LoginService.java, Scenchive/src/main/java/com/example/scenchive/member/service/MemberService.java
=> 개별 게시물 조회 구현 완료

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
=> 메인화면 향수 추천 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewListResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/Review.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
=> [Add] 향수 시향 후기 및 평가 서비스 (2차 구현)

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PTagDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTag.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PTagType.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
- #34 
- 필터 추천 화면에서 조회할 키워드 반환
=> [Feat] 필터 검색 키워드 반환

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/perfumeMarkedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
- #36 
- 마이페이지에서 북마크한 향수를 조회할 수 있는 기능
- 마이페이지에서 북마크한 향수와 유사한 향수를 추천받을 수 있는 기능
=> [Feat] 북마크 향수 조회 및 유사 향수 추천 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeRatingDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/Review.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java, Scenchive/src/main/resources/application.properties
- closed #33 
- 리뷰 데이터를 바탕으로 개별 향수의 평점평균 산출 로직을 구현하였습니다.
- 별점, 지속력, 확산력, 계절감 : 총점 5점을 기준으로 평균값을 계산합니다.
- 계절감 : 각 계절의 투표수를 카운트하여 백분율로 나타냅니다.
=> [Feat] 개별 향수 평가 평점평균 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/ProfileService.java
- #20 
- 띄어쓰기가 있는 브랜드의 경우 전체 브랜드명을 정확하게 적어야만 검색되는 문제 해결
=> [Fix] 향수 및 브랜드 검색 누락 문제 해결

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/info/dto/NotesInfoDto.java, Scenchive/src/main/java/com/example/scenchive/domain/info/dto/NotesInfoResponse.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumenote.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumenoteRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumescent.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/info/service/NotesService.java, Scenchive/src/main/resources/application.properties
=> [Feat] 개별 향수 노트 정보 조회 (1차 구현)

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumenote.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/Perfumescent.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentId.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/info/service/NotesService.java, Scenchive/src/main/resources/application.properties
=> [Fix] 개별 향수 노트 정보 조회 (2차 구현)

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/domain/shopping/dto/ItemDto.java
=> [Add] 온라인 최저가 쇼핑몰 연결 서비스 (2차 구현)

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
- #46 
- 향수 페이지에 들어갔을 때 사용자가 북마크한 향수인지 확인하는 기능
=> [Feat] 향수 북마크 유무 확인

Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java, Scenchive/src/main/resources/application.properties
- #36 
- 마이페이지에서 유저가 북마크한 향수 및 북마크한 향수와 유사한 향수를 조회할 때, 향수 아이디도 반환
=> [Fix] 마이페이지 북마크 향수 및 유사 향수 조회

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/utils/DeduplicationUtils.java
- #24 
- 추천 향수 반환 시 중복되는 향수가 제거되지 않는 문제 해결
=> [Fix] 추천 향수 반환 시 중복 향수 제거

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/UtagDtoList.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/UserTagRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/ProfileService.java
- #51
- 향수 프로필에서 수정하기 버튼을 눌렀을 때 키워드를 추가하거나 삭제할 수 있는 기능 구현
=> [Feat] 향수 프로필 키워드 수정 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/board/repository/Board.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/controller/CommentController.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/CommentDto.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/CommentRequest.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/Comment.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/CommentRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
- closed #50 
- 커뮤니티 댓글, 대댓글 기능 개발하였습니다.
=> [Feat] 커뮤니티 무한 댓글(대댓글) 구현

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTag.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagId.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/perfumeMarkedId.java, Scenchive/src/main/resources/application.properties
- #56 
- "identifier of an instance of was altered from~" 오류 수정
=> [Fix] 키워드 필터링 무한 스크롤 페이징 오류 수정

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/config/CorsConfig.java, Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/AuthorityDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/LoginForm.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/MemberForm.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/TokenDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/exception/DuplicateMemberException.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Authority.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/MemberRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/CustomUserDetailsService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/LoginService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/util/SecurityUtil.java, Scenchive/src/main/java/com/example/scenchive/jwt/JwtAccessDeniedHandler.java, Scenchive/src/main/java/com/example/scenchive/jwt/JwtAuthenticationEntryPoint.java, Scenchive/src/main/java/com/example/scenchive/jwt/JwtFilter.java, Scenchive/src/main/java/com/example/scenchive/jwt/JwtSecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/jwt/TokenProvider.java, Scenchive/src/main/resources/application.properties
- #59 
- JWT 토큰 추가
- 회원가입 시 DB에 비밀번호가 암호화되어 저장
- 로그인 시 토큰 반환
- userId 대신 토큰을 넣어 요청하도록 기존 코드 수정
- 향수 프로필 화면에서 북마크한 향수와 유사한 향수 추천 시 중복으로 추천해주는 문제 해결
=> [Feat] JWT 토큰 추가

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardSaveRequestDto.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java, Scenchive/src/main/resources/application.properties
- #62 
- 게시판 글 저장 시 member 정보 대신 토큰을 넘기도록 코드 수정
- 회원가입 시 키워드 받아오는 부분에서 토큰 없이 접근 가능하도록 코드 수정
=> [Fix] JWT 관련 코드 수정

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
- #64 
- 북마크 향수 조회 시 스크롤할 때 조회 결과를 10개씩 반환하도록 코드 수정
- 북마크 향수 조회 시 조회 결과로 나온 전체 데이터 수를 반환하는 코드 추가
- 북마크 향수와 유사한 향수 조회 시 스크롤할 때 조회 결과를 10개씩 반환하도록 코드 수정
- 북마크 향수와 유사한 향수 조회 시 조회 결과로 나온 전체 데이터 수를 반환하는 코드 추가 필요
=> [Add] 향수 프로필 북마크한 향수 및 유사 향수 조회 - 무한 스크롤 페이징

Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
- #64 
- 북마크한 향수와 유사한 향수 조회 시 전체 개수가 0개로 반환되는 오류 해결
=> [Fix] 향수 프로필 북마크한 향수와 유사한 향수 개수 반환

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/BrandDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchListDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Brand.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
- #20 
- 검색어가 브랜드명에 포함되는 경우 해당 브랜드의 향수 리스트 대신 브랜드명을 반환하도록 수정.
- 브랜드명 반환 시 영어와 한국어 모두 반환하도록 수정.
- 추후 이미지가 추가되면 이미지도 반환하도록 수정 필요.
=> [Fix] 검색 결과 반환값 수정

Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardListResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
- #3 
- 전체 게시판 조회 및 카테고리별 게시판 조회 기능에 페이징 구현
=> [Fix] 게시판 조회 페이징 구현

Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/CustomUserDetailsService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/ReviewDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
- #16 
- #74 
- 향수 리뷰 등록 요청 시 사용자 아이디 대신 토큰을 넘기도록 수정
- 메인 화면에서 사용자 닉네임을 조회할 수 있도록 하는 기능 추가
=> [Fix] 향수 리뷰 기능 수정 및 사용자 닉네임 조회 기능 추가

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/config/RedisConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/jwt/JwtFilter.java, Scenchive/src/main/java/com/example/scenchive/jwt/TokenProvider.java, Scenchive/src/main/resources/application.properties
- closed #73 
- redis 연결
- 로그인 시 access token을 redis에 저장
- 로그아웃 시 redis에 저장된 access token을 삭제 (토큰 무효화)
=> [Feat] 로그아웃 구현

Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/resources/application.properties
- #3 
- 게시글 조회 시 날짜 반환 형태를 "yyyy.MM.dd HH:mm"로 수정
=> [Fix] 개별 게시글 조회 시 날짜 반환형태 수정

Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
- #50 
- 게시글 조회 시 날짜 반환 형태를 "yyyy.MM.dd HH:mm"로 수정
=> [Fix] 댓글 조회 시 날짜 반환형태 수정

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java
- closed #81 
어플리케이션 초기 진입 시 필요한 토큰 유효성 검사 로직을 개발했습니다.
- 유효한 토큰이 있는 경우 : 해당 토큰 반환
- 토큰이 유효하지 않거나 만료된 경우 : 401 UNAUTHORIZED
=> [Feat] 토큰 유효성 검사 구현

Scenchive/src/main/java/com/example/scenchive/domain/board/dto/BoardDto.java, Scenchive/src/main/java/com/example/scenchive/domain/board/repository/BoardRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/MyCommentDto.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/CommentRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MyContentController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/MyContentListDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MyContentService.java, Scenchive/src/main/resources/application.properties
- closed #83 
개별 사용자가 작성한 글과 댓글을 조회하는 API를 개발했습니다.
=> [Feat] 사용자 작성글, 댓글 조회

Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
- closed #88 
- 소수점 첫째 자리까지 표시되도록 수정하였습니다.
=> [Fix] 개별 향수 평가 평점평균 수정

Scenchive/src/main/java/com/example/scenchive/domain/member/dto/ProfileDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/ProfileService.java, Scenchive/src/main/resources/application.properties
=> [Fix] 향수 프로필 사용자 인적사항 조회 수정

Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
- closed #91 
- 시향 후기 목록이 최신순으로 노출되도록 수정하였습니다.
=> [Fix] 시향 후기 정렬 기준 수정 

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java
- #86 
- 메인화면 향수 추천 api에서 이미지 객체 반환 시 공백 제거 후 반환되도록 수정
=> [Fix] 향수, 브랜드 이미지 객체 반환 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/MainPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PersonalDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/dto/BookmarkPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java, Scenchive/src/main/resources/application.properties
- closed #94 
- 기존 영어 버전의 브랜드명과 함께 한글 번역 데이터를 보낼 수 있도록 코드를 수정했습니다.
=> [Add] 브랜드명 한글 번역 변수 추가

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/resources/application.properties
- #94 
- 메인화면에서 추천 향수 반환 시 발생하는 오류 해결
=> [Fix] 메인화면 향수 추천 한글 브랜드명 반환 오류 해결

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java
- closed #94 
- DTO 한글 번역 변수 순서 변경 이슈 수정했습니다.
=> DTfix: DTO 한글 번역 변수 순서 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/resources/application.properties
- closed #99 
- 브랜드 한글 검색 기능을 개발하였습니다.
=> [Feat] 브랜드 한글 검색 기능 추가

Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java, Scenchive/src/main/resources/application.properties
- #102 
- 이미지만 받아와서 저장하는 기능 구현
=> [Feat] 이미지 업로드 테스트 기능

Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
- #3 
- 카테고리별 게시판 조회 시 게시물이 내림차순 정렬되도록 수정
=> [Fix] 카테고리별 게시판 조회 내림차순 정렬

Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/resources/application.properties
- #14 
- 향수 프로필 화면에서 추천 향수 반환 시 최대 개수를 10개로 제한
=> [Fix] 향수 프로필 추천 향수 최대 개수 설정

Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/domain/board/dto/TotalBoardResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java, Scenchive/src/main/resources/application.properties
- closed #106 
- 전체 게시글 수 반환 코드 추가
- 카테고리별 게시글 수 반환 코드 추가
=> [Add] 커뮤니티 게시글 수 반환

Scenchive/src/main/java/com/example/scenchive/domain/board/service/BoardService.java
- closed #108 
- 게시글 총 개수가 아닌 페이징된 게시글 수를 반환하는 이슈 해결하였습니다.
=> [Fix] 커뮤니티 게시글 수 반환 수정

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/BookmarkService.java, Scenchive/src/main/resources/application.properties
- #36 
- 향수 프로필 화면에서 북마크한 향수와 유사한 향수 추천 시 최대 10개까지만 추천
=> [Fix] 향수 프로필 유사 향수 추천 개수 제한

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeFullInfoDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
- closed #110 
- 향수 전체 정보 반환하는 api 입니다.
=> [Feat] 향수 전체 정보 반환

Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
- #10 
- 리뷰가 등록되어있지 않은 향수의 경우 별점을 0점으로 설정
=> [Fix] 향수 별점순 정렬 기능 수정

Scenchive/src/main/java/com/example/scenchive/domain/comment/dto/CommentDto.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java
- #83 
- 댓글 조회 시 댓글 작성자 id값도 반환하도록 수정
=> [Fix] 댓글 조회 기능

Scenchive/src/main/java/com/example/scenchive/domain/comment/repository/CommentRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/controller/NotificationController.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/dto/NotificationDto.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/dto/ResponseNotificationDto.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/repository/Notification.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/repository/NotificationRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/service/NotificationService.java
- #123 
- 유저별 알림 목록 조회 기능, 알림 클릭시 알림 check값 true로 변환하는 기능, 알림 확인 유무 확인 기능, 일주일 지난 알림 삭제 기능 추가
=> [Feat] 알림 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/notification/service/NotificationService.java
=> [Feat] 알림 기능 예외 추가

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/domain/filter/config/ChatGptConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/config/RestClientConfiguration.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/GPTController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/ChatGptMessage.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/ChatGptRequestDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/ChatGptResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/MainPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeFullInfoDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PersonalDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/QuestionRequestDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/GPTService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/resources/application.properties
=> [Fix] 향수 한글 번역명 추가 및 기능 수정

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/board/repository/Board.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/service/CommentService.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PersonalService.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/dto/NotificationDto.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/repository/Notification.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/service/NotificationService.java
- #123 
- 알림 내용에 글 id값 추가
- 비로그인시 메인화면에 랜덤향수 6개 반환
=> [Fix] 알림 내용 수정 및 랜덤향수 6개 반환 기능 추가

Scenchive/src/main/java/com/example/scenchive/domain/notification/dto/NotificationDto.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/service/NotificationService.java
=> [Fix] 알림 내용에 글 제목 추가

Scenchive/src/main/java/com/example/scenchive/domain/notification/controller/NotificationController.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/dto/NotificationDto.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/service/NotificationService.java
=> [Fix] 알림 페이징 추가

Scenchive/build.gradle, Scenchive/src/main/resources/application.properties
=> [Fix] 배포용 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Brand.java
=> [Fix] brand_url 컬럼 추가

Scenchive/src/main/java/com/example/scenchive/config/CorsConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/board/controller/BoardController.java, Scenchive/src/main/java/com/example/scenchive/domain/comment/controller/CommentController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/BookmarkController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/LoginController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MyContentController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/ProfileController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java, Scenchive/src/main/java/com/example/scenchive/domain/notification/controller/NotificationController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/shopping/controller/SearchRequestController.java
- corsconfig 클래스 수정
- @CrossOrigin 어노테이션 수정
-
=> [Fix] cors 에러 해결

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java
- 토큰 권한 필요하지 않은 API 수정
1. 메인화면 - 향수/브랜드 조회
2. 브랜드별 향수 리스트 조회
3. 향수 키워드 필터링검색
4. 향수 키워드 필터링 검색 - 키워드 조회
5. 개별 향수 시향 후기 목록 조회
6. 개별 향수 평점평균 산출
7. 온라인 최저가 상품 목록 조회
8. 개별 향수 노트 정보 조회
9. 향수 전체 정보 반환
=> [Fix] 토큰 권한 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
=> [Fix] 반환값에 brand_url 추가"

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchPerfumeDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
=> [Fix] 반환값에 브랜드 이미지 url 추가

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchListDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/exception/BrandSearchException.java, Scenchive/src/main/resources/application.properties
- 검색어에 대괄호가 들어갔을 때 발생하는 에러 수정.
=> [Fix] 브랜드 검색 시 에러 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeTagRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
- #10 
- 파라미터로 전달 받은 태그를 모두 가지고 있는 향수만 반환하도록 수정.
=> [Fix] 향수 필터링 추천 기능 수정.

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/board/service/S3Uploader.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/AdminController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/BrandDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/BrandRegDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeSaveDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Brand.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/BrandRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/resources/application.properties
=> [Feat] 관리자 기능 추가

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/AdminController.java, Scenchive/src/main/java/com/example/scenchive/domain/info/dto/PerfumescentDto.java, Scenchive/src/main/java/com/example/scenchive/domain/info/service/NotesService.java
- 관리자 계정으로 노트 추가 기능 추가
- 향수id, 노트 한글 이름, 영어 이름, 탑/미들/베이스 id값 추가하여 등록
=> FEAT: 관리자 계정으로 노트 추가 기능 추가

Scenchive/build.gradle, Scenchive/src/main/resources/application.properties
=> [Feat] 이메일 인증 설정

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/EmailController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/EmailService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/VerificationService.java, Scenchive/src/main/resources/application.properties
- #148 
- 알파벳 대소문자, 숫자, 특수 기호를 포함한 8자리 수 인증 코드 랜덤 생성
- 입력받은 이메일로 전송
- 유효기간 5분 내 이메일 검증 
- application.properties SMTP 설정 수정 주의
=> [Feat] 이메일 인증 및 검증 기능 추가

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/EmailService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
=> 151 feat 비밀번호 찾기

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
- #156 
- 이메일 중복 확인
- 닉네임 중복 확인
=> Feat: 이메일, 닉네임 중복 확인

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeCollectedRequestDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeCollectedResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollected.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollectedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/utils/BrandMapper.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/repository/Member.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
#160 
- perfumecollected 테이블 추가
- 마이페이지 보유 향수 추가, 삭제, 조회 기능 구현
- 토큰 필요
=> Feat: 마이페이지 보유 향수 추가, 삭제, 조회 기능 구현

Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
=> Fix : 예외 상황 구현

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollectedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
#164 
- 가장 많이 보유된 향수 
- 가장 많이 보유된 향수 브랜드
- 가장 많은 향수를 보유한 유저 닉네임과 향수 개수
=> feat: 대시보드 보유 향수 및 브랜드, 최다보유 유저 조회

Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java
=> Fix: 사진 업로드 안 하면 기본 프로필사진 링크 대신 null 값 전송

Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeReviewCountDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
#169 
- 리뷰 많은 향수 top5 조회
- 리뷰 개수가 같은 경우 향수 이름순 오름차순 나열
=> 169 top5 리뷰 향수 조회

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/controller/PerfumeClickController.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/PerfumeClicked.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/PerfumeClickedMapping.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/PerfumeClickedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/Season.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/SeasonName.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/SeasonRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/service/PerfumeClickedService.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/service/SeasonService.java
=> 168 feat 클릭순 나열

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/controller/PerfumeClickController.java
=> Fix: 주소 변경

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollectedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/MemberService.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeReviewCountDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/repository/ReviewRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
#174 
- 최다 보유 향수 반환 데이터 수정
- 최다 보유 향수 브랜드 반환 데이터 수정
=> 174 fix 최다보유 향수 브랜드

Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollectedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
#176 
- 사용자 평균 보유 향수 개수 소수점 둘째자리까지 조회
=> Feat: 사용자 평균 보유 향수 개수

Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
=> Fix: 브랜드 이미지 수정

Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
#180 
- 브랜드 이미지, 향수 이미지 url 수정
=> Fix: 브랜드, 향수 이미지 url

Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
#182 
- 특정 브랜드(디올)이 추가된 경우 조회되지 않는 문제 해결
- 브랜드 이미지 url 수정
=> fix: 보유 향수 조회

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/NoteRequestDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java
=> 155 feat find note

Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/java/com/example/scenchive/domain/info/dto/ScentAndScentKr.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java
=> 184 feat 노트 정보 가져오기

Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeDetailsDto.java
#185 
- 리뷰 기반 향수 조회 구조 수정
- PerfumeCollectedResponseDto 수정
- 보유 향수 목록 조회 이미지 추가
=> fix: 리뷰기반 향수 조회, 보유 향수 목록 조회

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/PerfumeCollectedResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/dto/PerfumeDetailsDto.java, Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
#185 
- 리뷰 기반 향수 조회 구조 수정
- 보유 향수 조회 수정
=> fix: 리뷰 기반 조회, 보유 향수 조회

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/NoteValueDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java, Scenchive/src/main/java/com/example/scenchive/domain/info/repository/PerfumescentRepository.java
=> Feat: 검색어로 노트 검색

Scenchive/src/main/java/com/example/scenchive/domain/rank/controller/PerfumeClickController.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/BrandClicked.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/repository/BrandClickedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/service/PerfumeClickedService.java
=> 187 feat 인기 브랜드 조회

Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/SearchBrandDto.java
=> Feat: 브랜드 정보 담을 DTO

Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
=> Feat: 노트 정보 가져오기 - 페이징

Scenchive/src/main/java/com/example/scenchive/domain/review/service/ReviewService.java
#198 
- perfumeDetailsDto 매핑 시 perfumeName과 brandName이 바뀌어 들어간 문제 수정
=> fix: 향수 브랜드 이름 수정

Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/service/SearchService.java
=> fix: 노트 개수 추가

Scenchive/src/main/java/com/example/scenchive/domain/board/service/S3Uploader.java
=> Feat: 이미지 저장 url 변경

Scenchive/src/main/java/com/example/scenchive/domain/filter/service/PerfumeService.java
=> 202 feat 이미지 저장 url 변경

Scenchive/src/main/java/com/example/scenchive/domain/board/service/S3Uploader.java
=> Feat: 이미지 url에서 파일명 추출 후 S3에서 이미지 삭제

Scenchive/Dockerfile, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/MyTopNotesResponseDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/dto/NoteWithCountDto.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/Perfume.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/repository/PerfumeCollectedRepository.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/service/PerfumeCollectedService.java
내가 가장 선호하는 노트 Top3 조회 API 추가
- MyTopNotesResponseDto  생성
응답 속도 개선 필요
=> FEAT: 내가 가장 선호하는 노트 Top3 조회 API 추가

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/global/health/HealthCheckController.java
#214 
- /health health check 추가 
- mysql 중복 의존성 수정 
- /health 인증 추가
=> feat: health check controller

Scenchive/build.gradle, Scenchive/src/main/java/com/example/scenchive/config/SecurityConfig.java, Scenchive/src/main/java/com/example/scenchive/config/SwaggerConfig.java, Scenchive/src/main/java/com/example/scenchive/domain/filter/controller/PerfumeController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/AuthController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/EmailController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/MemberController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/PerfumeCollectedController.java, Scenchive/src/main/java/com/example/scenchive/domain/member/controller/SurveyController.java, Scenchive/src/main/java/com/example/scenchive/domain/rank/controller/PerfumeClickController.java, Scenchive/src/main/java/com/example/scenchive/domain/review/controller/ReviewController.java, Scenchive/src/main/java/com/example/scenchive/domain/shopping/controller/SearchRequestController.java, Scenchive/src/main/java/com/example/scenchive/global/health/HealthCheckController.java, Scenchive/src/main/resources/application.properties
=> Fix/#217 환경변수 설정
